version: '3'
services:
  api:
    build: src/backend
    ports:
      - 8000:80
    volumes:
      - ./src/backend/db.json:/code/db.json
      - /sys:/sys
    devices:
      - /dev/gpiomem
    restart: always
  app:
    build: src/frontend
    ports:
      - 3000:3000
    volumes:
      - ./src/frontend/.env:/app/.env
    restart: always