version: '3'
services:
  api:
    build: /src/backend
    ports:
      - 8000:80
    volumes:
      - $USERPROFILE\git\pi-plant-watering\src\backend\db.json:/code/db.json
  app:
    build: /src/frontend/pi-plant-watering
    ports:
      - 3000:3000
    